### PR TITLE
5 new questions are added

### PR DESCRIPTION
**Pull request by avanish460**

### CODE REVIEW

**Comment by avanish460** [comment]
hey, @kunal-kushwaha I've added five more questions based on the pattern. So, please review it and merge it.

**Review by imminal35 — COMMENTED** [review]
Hey, I think Pattern #28 and #30 are not clear. Please ignore if this is what you supposed to add. 
Thanks.

**Comment by avanish460** [comment]
hey, @imminal35 everything is okay you need to view it as a file.

**Comment by kunal-kushwaha** [comment]
added I think, but feel free to make a new PR the file now has clear patterns

**Pull request closed without merging**
