### PR TITLE
Added handwritten notes for lecture 4 and lecture 5

### PR DESCRIPTION
**Pull request by Vrukshali-26**
Hey! I have added notes for lecture 4 : Introduction to Java
Check once!

### CODE REVIEW

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
javac is actually a part of JDK (in your diagram)

**Comment by Vrukshali-26** [comment]
Hey! I did the changes.

**Comment by kunal-kushwaha** [comment]
Thank You! The 3rd image of intro to java is blurry, can you please click it again?

**Comment by Vrukshali-26** [comment]
I changed the image. Can you check it once?

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket:

**Comment by kunal-kushwaha** [comment]
Thank You!

**Pull request merged**
