### PR TITLE
Questions on Binary Search

### PR DESCRIPTION
**Pull request by phantom-18**
I have hand picked some questions out of many from [LeetCode](https://leetcode.com/tag/binary-search/) which I think were beginner friendly and medium level on the concepts taught till now.

### CODE REVIEW

**Comment by phantom-18** [comment]
The link for the binary search video is still to be added after tomorrow's session

**Comment by kunal-kushwaha** [comment]
thanks! I will merge after the lecture

**Comment by kunal-kushwaha** [comment]
How are you? @phantom-18 can you please resolve the conflicts?

**Comment by phantom-18** [comment]
> How are you? @phantom-18 can you please resolve the conflicts?

Hey @kunal-kushwaha , I am sorry I didn't had my laptop from past 2 days. Can you help me how to resolve these conflicts. I watched your tutorial but in there you resolved the conflicts in the web only but in mine case its showing 
_These conflicts are too complex to resolve in the web editor_

**Comment by kunal-kushwaha** [comment]
Pull the branch on your system. Pull the main branch of the repo on your binary branch, it will then give conflicts. Resolve manually then make a commit and push. Let me know if you have any questions! This will be a good learning experience for you!

**Comment by phantom-18** [comment]
I pulled the branch but in mine 

> Pull the branch on your system. Pull the main branch of the repo on your binary branch, it will then give conflicts. Resolve manually then make a commit and push. Let me know if you have any questions! This will be a good learning experience for you!

I pulled the main branch in binary then when i looked into the searchig.md file it is showing no changes there. Your commits are not there, I mean everything is as it was before. And in git status it is showing me one unmerged path and its showing
_deleted by them: searching.md_

**Comment by imminal35** [comment]
Just in case if it helps 

# First Approach (Try as many times as possible, As mentioned by Kunal, You will learn from this). 
1. Pull Upstream(Main) into your local. 
2. Make changes manually to resolve conflicts. 
3. Commit your code. 

# Second Approach (Easy one, not recommended -:) )
1. Delete this PR.
2. Create new branch out of upstream , add your changes and raise new PR. 

Let me know if you want me to help you on this. Thanks

**Comment by phantom-18** [comment]
> Just in case if it helps
> 
> # First Approach (Try as many times as possible, As mentioned by Kunal, You will learn from this).
> 1. Pull Upstream(Main) into your local.
> 2. Make changes manually to resolve conflicts.
> 3. Commit your code.
> 
> # Second Approach (Easy one, not recommended -:) )
> 1. Delete this PR.
> 2. Create new branch out of upstream , add your changes and raise new PR.
> 
> Let me know if you want me to help you on this. Thanks

Deleting wont help me learn. I want to know what I am doing wrong

**Comment by phantom-18** [comment]
@kunal-kushwaha I have shared the ss on ticket-409 in the discord server.

**Comment by kunal-kushwaha** [comment]
I will look into this in the morning and share with you

**Comment by phantom-18** [comment]
> I will look into this in the morning and share with you

Okay no problem.

**Comment by kunal-kushwaha** [comment]
git checkout -b phantom-18-binary main
git pull https://github.com/phantom-18/DSA-Bootcamp-Java.git binary
git checkout main
git merge --no-ff phantom-18-binary
git push origin main

**Pull request merged**
