### PR TITLE
Modified reverseKGroup method so it does not reverse for less than k items

### PR DESCRIPTION
**Pull request by abhirajthakur**

### CODE REVIEW

**Review by kunal-kushwaha — COMMENTED** [review]
?

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
Is it submitting on LeetCode?

**Comment by abhirajthakur** [comment]
Yes it is submitting on leetcode.

**Comment by abhirajthakur** [comment]
Yes, it is submitting on leetcode.

**Pull request merged**
