### PR TITLE
array basic level questions. 

### PR DESCRIPTION
**Pull request by KukretiShubham**
These were some basic question I practised during my DSA journey.

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
@KukretiShubham I have mentioned this PR in some other PR's as well. They will be reaching out to you. Please make sure you add their questions as well. :slightly_smiling_face:

**Comment by KukretiShubham** [comment]
@kaiwalyakoparkar Sure, will add that.

**Comment by kaiwalyakoparkar** [comment]
@KukretiShubham Awesome :boom: . Also if you want you can convert this to a draft PR until it's under development :slightly_smiling_face: (Not doing this is also absolutely fine. It's just my suggestion)

**Comment by NimishKashyap** [comment]
Hello @KukretiShubham , can you add my questions in your PR?
[arrays.md](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/files/6965993/arrays.md)

**Comment by KukretiShubham** [comment]
@kaiwalyakoparkar I added question from #73 by @NimishKashyap . Please review.

**Review by NimishKashyap — CHANGES_REQUESTED** [review]
Please remove the hard question section as it is not required for now as mentioned by mentors. Others are good

**Comment by kunal-kushwaha** [comment]
thanks but we good for now

**Pull request closed without merging**
