### PR TITLE
Java Sample Questions for self improvement

### PR DESCRIPTION
**Pull request by DoyenPyth**
These are some Java Sample Questions for self improvement

### CODE REVIEW

**Comment by Vinoth6194** [comment]
@DoyenPyth Thanks. Those questions are great to work on our logic.

**Comment by Manish-kasera** [comment]
@DoyenPyth Thanks.Question will surely help folk.

**Comment by mayankv03** [comment]
@DoyenPyth Thanks buddy

**Comment by kunal-kushwaha** [comment]
Thank You!

**Pull request merged**
