### PR TITLE
Shivam assignment solution uploaded

### PR DESCRIPTION
**Pull request by shivamjaain**
Please add my assignment solution change to your main repo

### CODE REVIEW

**Comment by alokVerma749** [comment]
Every assignment problem is covered?

**Comment by shivamjaain** [comment]
as i am covering topic i upload more assignment
the link does not create any hurdel to repo 
so you can simply merge

**Comment by shivamjaain** [comment]
No one maintained the assignment solution in a well-structured format maybe I take some time to add all solutions but they were in a structured order 
Please sir, merge my pull request 😊

**Comment by kunal-kushwaha** [comment]
please add solutions first

**Pull request closed without merging**
