### PR TITLE
Question on pattern

### PR DESCRIPTION
**Pull request by phantom-18**
I have added some really good questions on **Patterns** which I think will help people get their hands good on loops.
It contains all level patterns from easy to hard.

### CODE REVIEW

**Comment by phantom-18** [comment]
@kunal-kushwaha Sorry, by mistake I removed the commits. Very Sorry

**Comment by phantom-18** [comment]
@kunal-kushwaha Updated now.

**Comment by nikhilreddydev** [comment]
bro, where is patterns.md file in assignments?

**Comment by kunal-kushwaha** [comment]
Thanks I will merge after the session

**Comment by phantom-18** [comment]
> bro, where is patterns.md file in assignments?

it has been renamed as patterns.txt

**Comment by kunal-kushwaha** [comment]
I did that

**Pull request merged**
