### PR TITLE
Git__GitHub_101.pdf is modified to Git_GitHub_102_modified.pdf some n…

### PR DESCRIPTION
**Pull request by avanish460**
…ew line are added

### CODE REVIEW

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket: Great Work :+1:

**Comment by PurneswarPrasad** [comment]
@avanish460 i raised an issue regarding  a line, do make this change too.
Refer here:
https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/issues/51#issue-962416751

**Comment by avanish460** [comment]
okay @PurneswarPrasad and thank you

**Comment by avanish460** [comment]
hey @PurneswarPrasad is this bug fixed because there are no changes that occur.
git cheatsheet change

**Comment by PurneswarPrasad** [comment]
@avanish460 someone else also opened a PR regarding the same. @kaiwalyakoparkar can you merge this?

**Pull request merged**
