### PR TITLE
SOLUTIONS OF 'FIRST JAVA PROGRAM' ASSIGNMENT.

### PR DESCRIPTION
**Pull request by chetan-2002**
Hey Kunal, I have added the solutions to all the problems of the second assignment. You can check it for once, if you find them correct you can merge them in the main repository. This is just for the reference for the people who got stuck at any problem.

### CODE REVIEW

**Review by kaiwalyakoparkar — CHANGES_REQUESTED** [review]
I am not able to see Ans 1 and Ans 2 :sweat_smile: Could you please cross-check with that?

**Comment by kaiwalyakoparkar** [comment]
Also @chetan-2002 a PR is already open for this #42

**Comment by chetan-2002** [comment]
Hi, @kaiwalyakoparkar, I don't think so that solutions are not visible because it's clearly visible in my forked repository. And I was the one who opened this pull request first i.e #41 .
If someone else could check if solutions are available or not it would be of great help.
Thanks in advance!

**Comment by kaiwalyakoparkar** [comment]
> Hi, @kaiwalyakoparkar, I don't think so that solutions are not visible because it's clearly visible in my forked repository. And I was the one who opened this pull request first i.e #41 .
> If someone else could check if solutions are available or not it would be of great help.
> Thanks in advance!

I understand and appreciate your work and efforts. But you should definitely check out #42 Which seems more convenient for beginners to look for answers.

**Comment by chetan-2002** [comment]
Thanks for the comment @kaiwalyakoparkar. I would try to make my code more beginner-friendly next time.

**Comment by kaiwalyakoparkar** [comment]
@chetan-2002 yeah! And beginners won't feel comfortable reading code solutions from pdf. As when there is direct code they can copy and paste to find the problem or something like that. You can close this PR if you want :)

**Comment by chetan-2002** [comment]
I just made my solutions in form of a pdf just because otherwise it would just become a copy-paste material. I was just having the thought that providing the copy-paste material would not help anyone. If you still believe that I should close this pull request, then just me a nod, I would do it. Cheers!

**Pull request closed without merging**
