### PR TITLE
notes-website added

### PR DESCRIPTION
**Pull request by Utkarsh1504**
A website that will contain all the DSA-Bootcamp in the form of markdown.

### CODE REVIEW

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
can you please give course the credits in the website?

**Comment by Utkarsh1504** [comment]
Yes, I will add `DSA-Bootcamp-Java` course to the website for sure.

**Comment by Nilimasethi** [comment]
Hello Kunal Sir ….
when I have watched the function /method video one doubt is on my mind …can we swap the variable using function or method or not ??

**Comment by Utkarsh1504** [comment]
@kunal-kushwaha I have added it on the Welcome Page. Please have a look at https://utkarsh1504.github.io/DSA-Java/introduction#prerequisites
Thank you!

**Pull request merged**
