### PR TITLE
Update InfiniteArray.java for element 0 and 1

### PR DESCRIPTION
**Pull request by shapnesht**

### CODE REVIEW

**Review by imminal35 — COMMENTED** [review]
Seems to be a duplicate PR. One PR is already opened with same work however he has implemented simple if-else statement.

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
line 43 will not execute

**Comment by shapnesht** [comment]
@kunal-kushwaha deleted the file

**Comment by shapnesht** [comment]
@kunal-kushwaha updated the file

**Comment by kunal-kushwaha** [comment]
I don't know the use of this, the code works for me

**Pull request closed without merging**
