### PR TITLE
lesson 5: Fixed bug in Prime code

### PR DESCRIPTION
**Pull request by Deveshb15**
The while loop skipped the condition for perfect square and exited the code, so I added a less than equal to operator so that it even checks for perfect square!

### CODE REVIEW

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket:

**Review by chetan-2002 — COMMENTED** [review]
Now you can also remove the edge case for n==4. Because when c=2,c*c=4, and it would enter inside the while loop, and 4%4=0, then then the program will print, Not prime and that's the answer that we wanted.

**Comment by Deveshb15** [comment]
> Now you can also remove the edge case for n==4. Because when c=2,c*c=4, and it would enter inside the while loop, and 4%4=0, then then the program will print, Not prime and that's the answer that we wanted.

Will make the changes, thank you for bringing this to my notice!

**Comment by Deveshb15** [comment]
@kaiwalyakoparkar review this please!

**Pull request merged**
