### PR TITLE
Adding handwritten notes of lecture 2 and lecture 3

### PR DESCRIPTION
**Pull request by Vrukshali-26**
I have created notes for below two lectures : 
> Introduction to Programming Languages
> Flow of Program
Do check once !

### CODE REVIEW

**Comment by kunal-kushwaha** [comment]
Hey, thanks for this! Can you please rename the file to "Handwritten notes" or something?

**Comment by Vrukshali-26** [comment]
I did required changes can you check once!

**Comment by kunal-kushwaha** [comment]
Thank You!

**Comment by imminal35** [comment]
@Vrukshali-26  - Notes are really good, Captured all things from video. Good Work.

**Review by aniruddhabagal — COMMENTED** [review]
These handwritten notes are great!👍

**Pull request merged**
