### PR TITLE
Added handwritten notes for functions/methods

### PR DESCRIPTION
**Pull request by Vrukshali-26**

### CODE REVIEW

**Comment by kunal-kushwaha** [comment]
Thanks! Actually return type can be anything, not just primitives. Also void is a return type, it's not no return type. We use void when we don't need to return anything.

**Comment by Vrukshali-26** [comment]
hey kunal!
in return_type part it is written like : it may be primitive or void type and in bracket void type (returns nothing) means don't need to return anything. ig it's right! Can you check again?

**Comment by imminal35** [comment]
As usual great Work !!!

Just a small observation. On second last page, Where you are explaining about VarArgs. you're declaring a function of type void and you have mentioned that result should be of type int[ ]. 

May be you can ignore this observation as its like net-picking but I thought to share. You can change "result" to "Parameters". (Assuming you were talking about Parameters) 
Thanks.

**Comment by kunal-kushwaha** [comment]
@Vrukshali-26 could you please make the changes and update the PR when you get time? thank you!

**Comment by Vrukshali-26** [comment]
@imminal35 thanks! 
@imminal35 and @kunal-kushwaha I have made the required changes please check once

**Comment by imminal35** [comment]
Hey @Vrukshali-26  This looks good now, Thanks !!!

**Pull request merged**
