### PR TITLE
Git__GitHub_101.pdf deleted Git__GitHub_101(edited).pdf added with a …

### PR DESCRIPTION
**Pull request by ANURAG-PATHAK**
…modification on page 2 point 9

### CODE REVIEW

**Comment by avanish460** [comment]
hey @ANURAG-PATHAK, where are you did the change?
git cheatsheet change

**Comment by ANURAG-PATHAK** [comment]
> hey @ANURAG-PATHAK, where are you did the change?
> git cheatsheet change

I changed the line below the red text 
before(old): all the commits or changes before this will go back to the unstaged area now

after(new): all the commits or changes after this will go back to the unstaged area now

**Comment by ANURAG-PATHAK** [comment]
> hey @ANURAG-PATHAK, where are you did the change?
> git cheatsheet change

since this is my first contribution on GitHub if I did something wrong then please can you guide me through

**Comment by PurneswarPrasad** [comment]
@ANURAG-PATHAK i have mentioned this correction in an earlier PR, so you may close this PR to reduce hassle, Nevertheless, good job!

**Comment by ANURAG-PATHAK** [comment]
> @ANURAG-PATHAK I have mentioned this correction in an earlier PR, so you may close this PR to reduce hassle, Nevertheless, good job!

okay, thank you

**Comment by kunal-kushwaha** [comment]
Thanks but duplicate PR

**Pull request closed without merging**
