### PR TITLE
Update 08-strings.md

### PR DESCRIPTION
**Pull request by avanish460**

### CODE REVIEW

**Comment by kunal-kushwaha** [comment]
@avanish460  why did you skip so many questions? i mentioned on discord put all string questions that contain tags that we have done so far. even just 'String' tag questions are skipped.

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
thanks! but why did you skip so many questions? i mentioned on discord put all string questions that contain tags that we have done so far. even just 'String' tag questions are skipped.

**Comment by avanish460** [comment]
okay
I will abb that question later because I am busy with hackthon

**Comment by Manish-kasera** [comment]
@avanish460 Doing a great job Brother.. I think he will add these questions after he do String problem video.

**Pull request closed without merging**
