### PR TITLE
adding questions for dsa from every topic with links

### PR DESCRIPTION
**Pull request by sumitmukharjeeeeee**
hyy team added many questions for dsa ranging from array linked list sorting dp and many more with links to it

### CODE REVIEW

**Review by chetan-2002 — COMMENTED** [review]
Hey @sumitmukharjeeeeee  you have collected a handful number of question and that is great, but I think only question to those concepts should be added which has already been taught. Cheers!

**Comment by sumitmukharjeeeeee** [comment]
Yeah I know but I thought As we move forward we could do 2 or 4 questions everyday for the topic taught with our own pace.

**Comment by kaiwalyakoparkar** [comment]
> Yeah I know but I thought As we move forward we could do 2 or 4 questions everyday for the topic taught with our own pace.

I guess chetan is correct. If we add questions beforehand there are many people who will get confused regarding the scope of the question

**Comment by sumitmukharjeeeeee** [comment]
> > Yeah I know but I thought As we move forward we could do 2 or 4 questions everyday for the topic taught with our own pace.
> 
> I guess chetan is correct. If we add questions beforehand there are many people who will get confused regarding the scope of the question

All right I will make this request later

**Comment by SP-XD** [comment]
This curated list of questions are from love buber youtuber.

**Pull request closed without merging**
